# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/users/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Carss",
    "email": "Adamd3sadsa11254@test.com",
    "password": "12345678",
    "amountMoney": "10000",
    "currency": "PLN"
}
###

PUT http://localhost:8080/account/1/charge
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZGFtZDNzYWRzYTExMjU0QHRlc3QuY29tIiwiaWF0IjoxNTQ2OTg0NzA3LCJpZCI6ImNjYzFmZTI0LTYxYzgtNDQ4MS05YTkzLWM1MjIyZjczM2Q4MiJ9.EoAozyfk3T_GSQ3jEwUtI55WyoMfFwlUTmyZt71havQ
Content-Type: application/json

{
    "amount": "90",
    "currency": "PLN"
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "Adamd3sadsa11254@test.com",
    "password": "12345678"
}

###

DELETE http://localhost:8080/users/logout?uuid=bbc41727-ffa8-410f-be5b-1cc3d5e3f9f2

###

