# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/users/register
Content-Type: application/json

{
    "name":{
        "firstName": "Greg",
        "lastName": "KER"
    },
    "email": {
        "value": "Aaamd3sadsa1125114@test.com"
    },
    "password": {
        "value": "12345678"
    },
    "money": {
        "amount": "10000.11",
        "currency": "PLN"
    }
}
###

PUT http://localhost:8080/account/1/charge
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBYWFtZDNzYWRzYTExMjUxMTRAdGVzdC5jb20iLCJpYXQiOjE1NDcxNDY0NzMsImV4cCI6MTU0NzE0ODI4MCwiaWQiOiJjM2ZhOTYzMy03MGUxLTQ1NDQtODYzMC0wMmUzOGYzOTdhOWEiLCJhY2NvdW50X2lkIjoxfQ.VhotL2LyFaEvrpCp5xvCAfV6HPOjbwK_SAO0-V2r0Cs
Content-Type: application/json

{
    "amount": "10000.11",
    "currency": "PLN"
}

###

PUT http://localhost:8080/account/1/transfer/57836297789354525850468666/charge
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBYWFtZDNzYWRzYTExMjUxMTRAdGVzdC5jb20iLCJpYXQiOjE1NDcwNzEwNTYsImV4cCI6MTU0NzA3Mjg1NiwiaWQiOiIzNjg0ZTc3OC1iMjgyLTQ3YjAtOTY0Zi0wMmJkNjA4ZjhlYjAiLCJhY2NvdW50X2lkIjoxfQ.xy698XsMzviDqJqaQaiHjjSvt2LMsj0R3anwTE1BC4c
Content-Type: application/json

{
    "amount": "11.99",
    "currency": "PLN"
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "Aaamd3sadsa1125114@test.com",
    "password": "12345678"
}

###

DELETE http://localhost:8080/users/logout?uuid=3684e778-b282-47b0-964f-02bd608f8eb0

###

